In [2]:
import numpy.matlib
import numpy as np
import math

In [5]:
X = np.loadtxt('./data/x.dat')

In [6]:
Y = np.loadtxt('./data/y.dat')[np.newaxis]

In [8]:
Y = np.transpose(Y)

In [116]:
def magsqr(x): 
    return sum(i**2 for i in x)

In [129]:
def lwlr(x_train, y_train, x, tau):
    m = x_train.shape[0]
    n = x_train.shape[1]
    theta = np.zeros([2,1])
    lmbda = 0.0001
    w = np.zeros([m,1])
    for i, xi in enumerate(x_train):
        w[i] = np.exp(-magsqr(xi-x)/2/tau/tau)
    print(w)
    print("######################################")
    ##g is first derivative  
    g = np.ones([n,1])
    i = 1
    while(math.sqrt(magsqr(g)) > 1e-06):
        #logistic regression function htheta
        print(i)
        print("#########h############")
        h = 1 / (1+np.exp(-np.dot(x_train,theta)))
        print(h)
        print("#########g###########")
        g = np.dot(np.transpose(x_train),w*(y_train-h)) - lmbda*theta
        print(g)
        print("#########D#########")
        D = np.diag(np.transpose(-w*h*(1-h))[0])
        print(D)
        print("######Hessian#####")
        H = np.dot(np.dot(np.transpose(x_train),D),x_train) - np.diag(lmbda*np.ones(n))
        print(H)
        print("#######theta#######")
        theta -= np.dot(np.linalg.inv(H),g)
        print(theta)
        i+=1
       
    
    return (1 / (1+np.exp(-np.dot(x,theta))))[0]

In [143]:
lwlr(X,Y,[1.6359447e-01, -9.2105263e-01],0.1)

[[1.72490395e-75]
 [6.02544824e-55]
 [2.12401290e-33]
 [2.54791684e-24]
 [4.62685481e-19]
 [6.17385059e-12]
 [9.94958586e-04]
 [1.00000000e+00]
 [4.25098755e-03]
 [8.35105575e-09]
 [2.14684615e-13]
 [1.37897838e-24]
 [4.61804216e-46]
 [6.70873574e-64]
 [9.07215412e-72]
 [3.33940126e-29]
 [2.98662430e-18]
 [1.02693212e-21]
 [4.30525905e-13]
 [3.05076618e-05]
 [3.72087866e-06]
 [1.23150741e-11]
 [1.47868190e-01]
 [4.92203202e-08]
 [6.44083797e-17]
 [2.05829701e-38]
 [4.03851912e-48]
 [4.76959598e-62]
 [4.45332258e-74]
 [1.20717948e-60]
 [1.11053970e-26]
 [6.75173334e-70]
 [2.38494914e-52]
 [2.14585830e-38]
 [7.47903248e-35]
 [6.72363519e-33]
 [5.02847062e-26]
 [2.29961298e-21]
 [1.99110691e-08]
 [1.37506814e-14]
 [2.19682562e-23]
 [2.73288871e-18]
 [6.78633189e-34]
 [1.08100691e-67]
 [5.17109492e-55]
 [3.28516637e-49]
 [4.73021733e-54]
 [5.05024741e-81]
 [2.30478190e-86]
 [7.50376412e-45]
 [1.20113812e-27]
 [6.49279500e-45]
 [6.88786233e-33]
 [3.39992545e-42]
 [7.50952626e-70]
 [2.554476

0.9889578401723618

In [1]:
np.ones([10,1])

NameError: name 'np' is not defined

In [9]:
Y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [4]:
np.transpose(np.ones([1,10]))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])